### ISSUE TITLE
bindfs required after Yosemite updrade 

### ISSUE THREAD

**Issue by romsson** [cid-harvard/atlas-playbooks#1]
Error log:

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'bindfs'.

Fix:

vagrant plugin install vagrant-bindfs

**Comment by makmanalp** [comment]
Added to instructions!
